name: Ameba

on:
  push:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ameba-version: [v1.6.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.15.1

      - name: Cache Ameba binary
        id: cache-ameba
        uses: actions/cache@v4.2.2
        with:
          path: bin/ameba${{ runner.os == 'Windows' && '.exe' || '' }}
          key: ${{ runner.os }}-ameba-${{ matrix.ameba-version }}

      - name: Build Ameba
        if: steps.cache-ameba.outputs.cache-hit != 'true'
        run: |
          git clone --branch ${{ matrix.ameba-version }} --single-branch https://github.com/crystal-ameba/ameba.git
          cd ameba
          make bin/ameba CRFLAGS='-Dpreview_mt --no-debug'
          mkdir -p ../bin
          mv bin/ameba${{ runner.os == 'Windows' && '.exe' || '' }} ../bin/
          cd ..
          ${{ runner.os == 'Windows' && 'Remove-Item -Path "ameba" -Recurse -Force' || 'rm -rf ameba' }}

      - name: Run Ameba Linter
        run: bin/ameba${{ runner.os == 'Windows' && '.exe' || '' }} -c .ameba.yml ${{ runner.os == 'Windows' && '--except Layout/TrailingWhitespace,Lint/Formatting' || '' }}
